### ISSUE TITLE
Your Discord ID

### ISSUE THREAD

**Issue by dogete** [TheRiddler2/TheRiddler2#1]
For Collab

**Comment by TheRiddler2** [comment]
> For Collab

Hey! Contact me at https://discord.com/invite/vAeF6BqQ

**Comment by dogete** [comment]
Invite Invalid or Expired

**Comment by dogete** [comment]
I wanna Collab with you on Making a  Discord RAT

**Comment by TheRiddler2** [comment]
> I wanna Collab with you on Making a  Discord RAT

Apologies for the wrong invite. My discord username is "the_r1ddler_". Please give me a friend request and I'll get back to you shortly.

**Comment by dogete** [comment]
![image](https://github.com/user-attachments/assets/bb0d6eac-88a3-4df3-8015-31421ab4c8ef)

**Comment by dogete** [comment]
My Discord ID:- 

chess_master2358

**Comment by TheRiddler2** [comment]
> My Discord ID:-
> 
> chess_master2358

Sent a req!
